# true 1 和 false 0 
width: 1440             #图像宽度
height: 1080            #图像高度
Offset_x: 0             #X方向偏置
Offset_y: 0             #Y方向偏置

FrameRateEnable: true    #使能 
FrameRate: 200           #帧率

ExposureTime: 3000     #曝光时间

GainAuto: 17             #亮度的固定增益
